Use normal CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,18 +1,76 @@
 name: ci
 
-on: workflow_dispatch
+on:
+  push:
+    branches: [main]
+    tags: ["**"]
+  pull_request:
+    branches: [main]
+    types: [labeled, opened, synchronize, reopened]
+
+permissions: write-all
 
 jobs:
   build:
     name: ${{ matrix.config.variant }} ${{ matrix.config.target }}
     runs-on: ${{ matrix.config.os }}
-    timeout-minutes: 240
+    timeout-minutes: 180
     strategy:
+      # Always run main branch builds to completion. This allows the cache to
+      # stay mostly up-to-date in situations where a single job fails due to
+      # e.g. a flaky test.
+      # Don't fast-fail on tag build because publishing binaries shouldn't be
+      # prevented if 'cargo publish' fails (which can be a false negative).
+      fail-fast:
+        ${{ (github.event_name == 'pull_request' || (github.ref !=
+        'refs/heads/main' && !startsWith(github.ref, 'refs/tags/'))) &&
+        !contains(github.event.pull_request.labels.*.name, 'no-fail-fast') }}
       matrix:
         config:
-          - os: 'ubuntu-22.04'
+          - os: macOS-latest
+            target: x86_64-apple-darwin
+            variant: debug
+            cargo: cargo
+
+          - os: macOS-latest
+            target: x86_64-apple-darwin
+            variant: release
+            cargo: cargo
+
+          - os: ${{ github.repository == 'denoland/rusty_v8' && 'ubuntu-22.04-xl' || 'ubuntu-22.04' }}
+            target: x86_64-unknown-linux-gnu
+            variant: debug
+            cargo: cargo
+
+          - os: ${{ github.repository == 'denoland/rusty_v8' && 'ubuntu-22.04-xl' || 'ubuntu-22.04' }}
+            target: x86_64-unknown-linux-gnu
+            variant: release
+            cargo: cargo
+
+          - os: ${{ github.repository == 'denoland/rusty_v8' && 'windows-2019-xxl' || 'windows-2019' }}
+            target: x86_64-pc-windows-msvc
+            variant: release # Note: we do not support windows debug builds.
+            cargo: cargo
+
+          - os: ${{ github.repository == 'denoland/rusty_v8' && 'ubuntu-22.04-xl' || 'ubuntu-22.04' }}
+            target: aarch64-unknown-linux-gnu
+            variant: debug
+            cargo: cargo
+
+          - os: ${{ github.repository == 'denoland/rusty_v8' && 'ubuntu-22.04-xl' || 'ubuntu-22.04' }}
+            target: aarch64-unknown-linux-gnu
+            variant: release
+            cargo: cargo
+
+          - os: ${{ github.repository == 'denoland/rusty_v8' && 'ubuntu-latest-xl' || 'ubuntu-18.04' }}
+            target: aarch64-linux-android
+            variant: debug
+            cargo: cross
+
+          - os: ${{ github.repository == 'denoland/rusty_v8' && 'ubuntu-latest-xl' || 'ubuntu-18.04' }}
             target: aarch64-linux-android
             variant: release
+            cargo: cross
 
     env:
       V8_FROM_SOURCE: true
@@ -41,29 +99,31 @@ jobs:
           architecture: x64
 
       - name: Install cross compilation toolchain
-        if: matrix.config.target == 'aarch64-linux-android'
+        if: matrix.config.target == 'aarch64-unknown-linux-gnu'
         run: |
-          mkdir -p /home/runner/.local/bin
-          curl -qL https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-musl.tar.gz  | tar xz -C /home/runner/.local/bin
-          # ln -s /home/runner/.local/bin/cross /home/runner/.local/bin/cargo
-
-          sudo docker build --build-arg CROSS_BASE_IMAGE=ghcr.io/cross-rs/aarch64-linux-android:0.2.5 -t cross-rusty_v8:aarch64-linux-android .
+          rustup target add aarch64-unknown-linux-gnu
 
           sudo apt update
-          sudo apt install -yq unzip
-          # sudo apt install -yq --no-install-suggests --no-install-recommends \
-          #   binfmt-support g++-10-aarch64-linux-gnu g++-10-multilib \
-          #   gcc-10-aarch64-linux-gnu libc6-arm64-cross qemu qemu-user \
-          #   qemu-user-binfmt
+          sudo apt install -yq --no-install-suggests --no-install-recommends \
+            binfmt-support g++-10-aarch64-linux-gnu g++-10-multilib \
+            gcc-10-aarch64-linux-gnu libc6-arm64-cross qemu qemu-user \
+            qemu-user-binfmt
 
-          # sudo ln -s /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 \
-          #            /lib/ld-linux-aarch64.so.1
+          sudo ln -s /usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 \
+                     /lib/ld-linux-aarch64.so.1
 
-          # echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/aarch64-linux-gnu-gcc-10" >> ${GITHUB_ENV}
-          # echo "QEMU_LD_PREFIX=/usr/aarch64-linux-gnu" >> ${GITHUB_ENV}
+          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/aarch64-linux-gnu-gcc-10" >> ${GITHUB_ENV}
+          echo "QEMU_LD_PREFIX=/usr/aarch64-linux-gnu" >> ${GITHUB_ENV}
 
       - name: Write git_submodule_status.txt
         run: git submodule status --recursive > git_submodule_status.txt
+
+      - name: Install cross and build custom image
+        if: contains(matrix.config.target, "linux-android")
+        run: |
+          mkdir -p /home/runner/.local/bin
+          curl -qL https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-musl.tar.gz  | tar xz -C /home/runner/.local/bin
+          sudo docker build --build-arg CROSS_BASE_IMAGE=ghcr.io/cross-rs/${{ matrix.config.target }}:0.2.5 -t cross-rusty_v8:${{ matrix.config.target }} .
 
       - name: Cache
         uses: actions/cache@v3
@@ -125,50 +185,54 @@ jobs:
           . $basename/sccache --start-server
           echo "$(pwd)/$basename" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
 
-      - name: Build bin
-        run :
-          cross build -vv --bins --locked ${{ env.CARGO_VARIANT_FLAG }}
-          --target ${{ matrix.config.target }}
-
-      - name: Build lib
-        run :
-          cross build -vv --lib --locked ${{ env.CARGO_VARIANT_FLAG }}
-          --target ${{ matrix.config.target }}
-
-     # - name: Build bench
-     #   run :
-     #     cargo build -vv --benches --locked ${{ env.CARGO_VARIANT_FLAG }}
-     #     --target ${{ matrix.config.target }}
-
-      - name: Build test
-        run :
-          cross build -vv --tests --locked ${{ env.CARGO_VARIANT_FLAG }}
-          --target ${{ matrix.config.target }}
-
       - name: Test
         env:
           SCCACHE_IDLE_TIMEOUT: 0
         run:
-          cross test -vv --all-targets --locked ${{ env.CARGO_VARIANT_FLAG }}
+          ${{ matrix.config.cargo }} test -vv --all-targets --locked ${{ env.CARGO_VARIANT_FLAG }}
           --target ${{ matrix.config.target }}
 
       - name: Clippy
         run:
-          cross clippy --all-targets --locked ${{ env.CARGO_VARIANT_FLAG }}
+          ${{ matrix.config.cargo }} clippy --all-targets --locked ${{ env.CARGO_VARIANT_FLAG }}
           --target ${{ matrix.config.target }} -- -D clippy::all
 
       - name: Rustfmt
         run: cargo fmt -- --check
 
       - name: Prepare binary publish
-        run: gzip -9c
-          target/${{ matrix.config.target }}/${{ matrix.config.variant }}/gn_out/obj/${{ env.LIB_NAME }}.${{ env.LIB_EXT }} >
-          target/${{ env.LIB_NAME }}_${{ matrix.config.variant }}_${{ matrix.config.target }}.${{ env.LIB_EXT }}.gz &&
-          ls -l target/${{ env.LIB_NAME }}_${{ matrix.config.variant }}_${{ matrix.config.target }}.${{ env.LIB_EXT }}.gz
+        run: cp
+          target/${{ matrix.config.target }}/${{ matrix.config.variant }}/gn_out/obj/${{ env.LIB_NAME }}.${{ env.LIB_EXT }}
+          target/${{ env.LIB_NAME }}_${{ matrix.config.variant }}_${{ matrix.config.target }}.${{ env.LIB_EXT }}
 
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
+      - name: Binary publish
+        uses: softprops/action-gh-release@v0.1.15
+        if: >-
+          github.repository == 'denoland/rusty_v8' &&
+          startsWith(github.ref, 'refs/tags/')
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          name: my-artifact
-          path: target/${{ env.LIB_NAME }}_${{ matrix.config.variant }}_${{ matrix.config.target }}.${{ env.LIB_EXT }}.gz
-          retention-days: 5
+          files: target/${{ env.LIB_NAME }}_${{ matrix.config.variant }}_${{ matrix.config.target }}.${{ env.LIB_EXT }}
+
+      # TODO: add clang-format and maybe cpplint.
+
+      - name: Cargo Package
+        if: >-
+          github.repository == 'denoland/rusty_v8' &&
+          startsWith(matrix.config.target , 'x86_64') &&
+          matrix.config.variant == 'debug' &&
+          runner.os == 'Linux'
+        run: cargo package -vv --locked
+
+      - name: Publish
+        # Only publish on x64 linux when there's a git tag:
+        if: >-
+          startsWith(github.ref, 'refs/tags/') &&
+          github.repository == 'denoland/rusty_v8' &&
+          startsWith(matrix.config.target , 'x86_64') &&
+          matrix.config.variant == 'debug' &&
+          runner.os == 'Linux'
+        env:
+          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
+        run: cargo publish -vv
